### ISSUE TITLE
health check for fastcgi

### ISSUE THREAD

**Issue by lens0021** [femiwiki/nomad#332]
The example of WMF:[^1]

```yaml
  livenessProbe:
  {{- if eq .Values.php.fcgi_mode "FCGI_TCP" }}
    tcpSocket:
      port: 9000
  {{- else }}
{{/* TODO: add netcat-openbsd to the php image and run nc -U -z /run/shared/fpm-www.sock instead*/}}
    exec:
      command:
      - /usr/bin/test
      - -S
      - /run/shared/fpm-www.sock
  {{- end }}
    initialDelaySeconds: 1
    periodSeconds: 5
  {{- end }}
```

[^1]: https://gerrit.wikimedia.org/r/plugins/gitiles/operations/deployment-charts/+/400c67c2ad9ceb43d37017981a2b5b1e11560ef1/charts/mediawiki/templates/lamp/deployment.yaml.tpl#185
